development: &common
  enable_logging: yes
  autoload_paths:
    - app/models
    - app/services
  default_timezone: 'Pacific Time (US & Canada)'
  discount_after_N_jobs: [3, 9.99]

test:
  <<: *common
  enable_logging: no

staging:
  <<: *common

production:
  <<: *common
  enable_logging: no
